// define the syntax
syntax = "proto3";

// define the package name 
package wallet.v1;
// tells the generator to generate code for the Go programming
// language and specifies the import path for the generated code.
option go_package = "github.com/Muhmd95/Contracts/wallet/v1;walletv1";

import "google/protobuf/timestamp.proto";

service WalletService {
    rpc ModifyBalance(ModifyBalanceRequest) returns (ModifyBalanceResponse) {}
    rpc GetWallet(GetWalletRequest) returns (GetWalletResponse) {}
}

message ModifyBalanceRequest {
    string phone_number = 1;
    int64 amount = 2;

    string referenceID = 3; // the transaction id
}

message ModifyBalanceResponse {
    string wallet_id = 1;
    int64 balance = 2;
    
    google.protobuf.Timestamp updated_at = 3;
}

message GetWalletRequest {
    string phone_number = 1;
}

message GetWalletResponse {
    string wallet_id = 1;
    string owner_name =2;
    int64 balance = 3;
}

