// define the syntax

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: notifications/v1/notifications.proto

// define the package name

package notificationsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SendNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhoneNumber   string                 `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	TransactionId string                 `protobuf:"bytes,3,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	WalletId      string                 `protobuf:"bytes,4,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	Amount        int64                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	Balance       int64                  `protobuf:"varint,6,opt,name=balance,proto3" json:"balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotificationRequest) Reset() {
	*x = SendNotificationRequest{}
	mi := &file_notifications_v1_notifications_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationRequest) ProtoMessage() {}

func (x *SendNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_v1_notifications_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationRequest.ProtoReflect.Descriptor instead.
func (*SendNotificationRequest) Descriptor() ([]byte, []int) {
	return file_notifications_v1_notifications_proto_rawDescGZIP(), []int{0}
}

func (x *SendNotificationRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *SendNotificationRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendNotificationRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *SendNotificationRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *SendNotificationRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *SendNotificationRequest) GetBalance() int64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

type SendNotificationResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NotificationId string                 `protobuf:"bytes,2,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SendNotificationResponse) Reset() {
	*x = SendNotificationResponse{}
	mi := &file_notifications_v1_notifications_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationResponse) ProtoMessage() {}

func (x *SendNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notifications_v1_notifications_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationResponse.ProtoReflect.Descriptor instead.
func (*SendNotificationResponse) Descriptor() ([]byte, []int) {
	return file_notifications_v1_notifications_proto_rawDescGZIP(), []int{1}
}

func (x *SendNotificationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendNotificationResponse) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

var File_notifications_v1_notifications_proto protoreflect.FileDescriptor

const file_notifications_v1_notifications_proto_rawDesc = "" +
	"\n" +
	"$notifications/v1/notifications.proto\x12\x10notifications.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcc\x01\n" +
	"\x17SendNotificationRequest\x12!\n" +
	"\fphone_number\x18\x01 \x01(\tR\vphoneNumber\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12%\n" +
	"\x0etransaction_id\x18\x03 \x01(\tR\rtransactionId\x12\x1b\n" +
	"\twallet_id\x18\x04 \x01(\tR\bwalletId\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\x12\x18\n" +
	"\abalance\x18\x06 \x01(\x03R\abalance\"]\n" +
	"\x18SendNotificationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12'\n" +
	"\x0fnotification_id\x18\x02 \x01(\tR\x0enotificationId2\xf6\x01\n" +
	"\x13NotificationService\x12n\n" +
	"\x13SendSMSNotification\x12).notifications.v1.SendNotificationRequest\x1a*.notifications.v1.SendNotificationResponse\"\x00\x12o\n" +
	"\x14SendPushNotification\x12).notifications.v1.SendNotificationRequest\x1a*.notifications.v1.SendNotificationResponse\"\x00B?Z=github.com/Muhmd95/Contracts/notifications/v1;notificationsv1b\x06proto3"

var (
	file_notifications_v1_notifications_proto_rawDescOnce sync.Once
	file_notifications_v1_notifications_proto_rawDescData []byte
)

func file_notifications_v1_notifications_proto_rawDescGZIP() []byte {
	file_notifications_v1_notifications_proto_rawDescOnce.Do(func() {
		file_notifications_v1_notifications_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notifications_v1_notifications_proto_rawDesc), len(file_notifications_v1_notifications_proto_rawDesc)))
	})
	return file_notifications_v1_notifications_proto_rawDescData
}

var file_notifications_v1_notifications_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_notifications_v1_notifications_proto_goTypes = []any{
	(*SendNotificationRequest)(nil),  // 0: notifications.v1.SendNotificationRequest
	(*SendNotificationResponse)(nil), // 1: notifications.v1.SendNotificationResponse
}
var file_notifications_v1_notifications_proto_depIdxs = []int32{
	0, // 0: notifications.v1.NotificationService.SendSMSNotification:input_type -> notifications.v1.SendNotificationRequest
	0, // 1: notifications.v1.NotificationService.SendPushNotification:input_type -> notifications.v1.SendNotificationRequest
	1, // 2: notifications.v1.NotificationService.SendSMSNotification:output_type -> notifications.v1.SendNotificationResponse
	1, // 3: notifications.v1.NotificationService.SendPushNotification:output_type -> notifications.v1.SendNotificationResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_notifications_v1_notifications_proto_init() }
func file_notifications_v1_notifications_proto_init() {
	if File_notifications_v1_notifications_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notifications_v1_notifications_proto_rawDesc), len(file_notifications_v1_notifications_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notifications_v1_notifications_proto_goTypes,
		DependencyIndexes: file_notifications_v1_notifications_proto_depIdxs,
		MessageInfos:      file_notifications_v1_notifications_proto_msgTypes,
	}.Build()
	File_notifications_v1_notifications_proto = out.File
	file_notifications_v1_notifications_proto_goTypes = nil
	file_notifications_v1_notifications_proto_depIdxs = nil
}
